CREATE CONSTRAINT player_id IF NOT EXISTS FOR (p:Player) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT coach_id  IF NOT EXISTS FOR (c:Coach)  REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT club_id   IF NOT EXISTS FOR (c:Club)   REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT season_id IF NOT EXISTS FOR (s:Season) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT nation_name IF NOT EXISTS FOR (n:Nation) REQUIRE n.name IS UNIQUE;

CREATE INDEX player_name IF NOT EXISTS FOR (p:Player) ON (p.name);
CREATE INDEX club_name   IF NOT EXISTS FOR (c:Club)   ON (c.name);
